services:
  server:
    build:
      context: ./server/CatalogOfCoursesAndTeachers/CatalogOfCoursesAndTeachers
      dockerfile: Dockerfile
    container_name: courses-server
    ports:
      - "5231:5231"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build:
      context: ./client/courses-client
      dockerfile: Dockerfile
    container_name: courses-client
    ports:
      - "8000:80"
    depends_on:
      - server